# Generated by Django 5.2.16 on 2026-08-20 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLItemMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=50, unique=True)),
                ('ml_item_id', models.CharField(max_length=30, unique=True)),
                ('ml_site_id', models.CharField(default='MLC', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('paused', 'Pausado'), ('closed', 'Cerrado'), ('under_review', 'En revisión')], default='active', max_length=20)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Item publicado en Mercado Libre',
                'verbose_name_plural': 'Items publicados en Mercado Libre',
            },
        ),
        migrations.CreateModel(
            name='SkuSyncConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=50, unique=True)),
                ('sync_stock', models.BooleanField(default=False)),
                ('sync_price', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sku_sync_configs_editados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de sync por SKU',
                'verbose_name_plural': 'Configuraciones de sync por SKU',
            },
        ),
    ]
