# Generated by Django 5.2.16 on 2026-08-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_ml', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=200)),
                ('refresh_token', models.CharField(max_length=200)),
                ('expires_at', models.DateTimeField()),
                ('ml_user_id', models.BigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Token de Mercado Libre',
                'verbose_name_plural': 'Token de Mercado Libre',
            },
        ),
    ]
