# Generated by Django 5.2.16 on 2026-08-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_ml', '0003_configuracionsyncml'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilSellerML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil del seller en Mercado Libre',
                'verbose_name_plural': 'Perfil del seller en Mercado Libre',
            },
        ),
    ]
