# Generated by Django 5.2.16 on 2026-08-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_ml', '0004_perfilsellerml'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlitemmap',
            name='ultimo_precio_sincronizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
