# Generated by Django 5.2.16 on 2026-08-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_ml', '0005_mlitemmap_ultimo_precio_sincronizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlitemmap',
            name='precio_manual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='mlitemmap',
            name='unidades_por_item',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='skusyncconfig',
            name='porcentaje_ajuste_propio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='skusyncconfig',
            name='precio_manual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='mlitemmap',
            name='sku',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
